Endret alderStep + tester i henhold til UX-tilbakemeldinger
navikt/pensjonskalkulator-uinnlogget-frontend pull request #90
Opened 2024-11-18 11:10 UTC by 9maPiltan

Siden 0 skal være en tillat verdi, samtidig som at UX ønsker at inputfeltet skal være tomt når bruker ikke har skrevet inn noe, så må den initielle formstaten bli satt til en verdi som ikke er 0. Derfor er den satt til -1

2024-11-18 12:28 UTC, mlp73 requested changes

2024-11-18 12:50 UTC, 9maPiltan commented on src/defaults/defaultFormState.ts
>    boddIUtland: '', // fjernes fra ApiPayloaded
Utfordringen med det er jo at schemas som genereres fra backend da må bli modifisert til å tillate null (per nå er feks number og undefined tillatte verdier), og dermed forsvinner jo hensikten med å hente schema fra backend.

2024-11-20 15:31 UTC, mlp73 requested changes

2024-11-20 15:31 UTC, mlp73 commented on src/components/pages/InntektStep.tsx
> +                          ? null
Ref kommentar i common.d.ts skal denne ikke settes til null. Feltet er optional så det er nok undefined som gjelder.

2024-11-20 15:31 UTC, mlp73 commented on src/components/pages/AlderStep.tsx
> +            value={
Trenger vi å sette '' som verdi her? Feltet skal vel tåle undefined?

2024-11-20 15:31 UTC, mlp73 commented on src/common.d.ts
> +  boddIUtland: BooleanRadio | null
Bør følge samme konvensjon som du innførte med `harInntektVsaHelPensjon`.
Heter da: `harBoddIUtland`

2024-11-20 15:31 UTC, mlp73 commented on src/common.d.ts
> +export type State = Omit<
Jeg ser at sivilstand, inntekt før uttak og uttaksgrad er påkrevde felt i deres applikasjon, men dette gjenspeiles ikke i types. Der kan de være undefined. Dette bør gjøres noe med.

2024-11-20 15:31 UTC, mlp73 commented on src/helpers/useErrorHandling.ts
>  const useErrorHandling = (states: State) => {
`const useErrorHandling = (state: State)`
Ikke flertall

2024-11-20 15:31 UTC, mlp73 commented on src/helpers/useErrorHandling.ts
Linje 40 mangler tilpasninger til gradertUttak

2024-11-20 15:45 UTC, 9maPiltan commented on src/components/FormPage.tsx
> +  const [formState, setFormState] = useState<State>(initialState)
Du hadde vel tidligere godkjent dette i Martin sin PR?

2024-11-20 15:49 UTC, 9maPiltan commented on src/components/pages/AlderStep.tsx
> +            style={{ width: '6rem' }}
UX-fix har jeg droppet fra denne PR'en for det hadde blitt alt for mye. Det kommer i neste PR. I denne PR'en har fokuset skiftet mot refaktoreringen

2024-11-20 15:50 UTC, 9maPiltan commented on src/components/pages/InntektStep.tsx
>            {i + 1} måned
Skjønner! Den saken er på løpende bånd. Vi har planlagt en til UX-gjennomgang for å verifisere usikkerhetene fra forrige prat.

2024-11-20 15:53 UTC, 9maPiltan commented on src/components/pages/EktefelleStep.tsx
> +          <option value={undefined}>----</option>
Ops! Den glemte jeg å fikse opp i!

2024-11-20 17:00 UTC, mlp73 commented on src/components/FormPage.tsx
> +  const [formState, setFormState] = useState<State>(initialState)
Jeg må ærlig innrømme at jeg ikke husker hver eneste linje fra alle PR-er, og jeg håper det er greit! :) Det kan være mange grunner til at jeg godkjente en tidligere PR uten å kommentere på akkurat denne linjen. Jeg har tidligere prøvd å forklare hensikten med reviews: Det handler ikke om å peke på hva som er riktig eller galt. Selvfølgelig er det viktig å fange opp eventuelle store feil, men det handler også om å få et nytt perspektiv på koden – en form for frisk distanse.

I dette tilfellet er vi i en refaktorering, så det kan være at jeg legger mer merke til navngivning nå enn jeg gjorde tidligere. Kanskje var det noe jeg ikke reagerte på før fordi jeg ikke så helheten i PR'en, at konteksten har endret seg, eller at det har vært flere iterasjoner som har gradvis forbedret navnene. Tidligere var det kanskje noe med "skjema" og "formValues", og nå har det utviklet seg til å bli renere. Det kan også være at jeg rett og slett scrollet forbi første gang. 😊

Poenget er uansett at dette bare er innspill. Du står helt fritt til å gjøre det du ønsker med tilbakemeldingen, så lenge det ikke er snakk om direkte feil. En PR blir aldri holdt tilbake bare fordi man velger å ikke følge et innspill. Men det kan skje at en kommentar dukker opp i en senere PR fordi fokuset endrer seg. Til slutt er det din vurdering om du vil gjøre noe med innspillet eller ikke.

Så når det gjelder akkurat dette med navn i staten ser jeg på det slik at det bør henge sammen: Hvis staten heter formState, bør da typen også hete FormState, og default-staten bør da hete initialFormState. En typisk funksjon ville da hete doSomethingToFormState. Det er sånn jeg ville ihvertfall forvente å kunne å catche den røde tråden og navigere gjennom en kodebase. Nå har det vært ryddet opp en del og det kan se ut som at det landes i retning "state", med typen "State" og "initialState. Derfor min kommentar om å kalle det for 'state'/'setState' og gå vekk fra "form".

2024-11-20 17:02 UTC, mlp73 commented on src/components/pages/AlderStep.tsx
> +            style={{ width: '6rem' }}
Ok. Opprett gjerne ulike branch og flere PR så blir det enklere å forstå som reviewer :)

2024-11-25 11:54 UTC, mlp73 approved these changes
Approved med følgende tilbakemelding:

- Søke etter /* og // og rydd opp i kommentert kode.
- console.log hengende i submitForm og i useErrorHandling
- utenlandsAntallAar satt til -1 i useErrorHandling test. Det skal ikke være mulig?
- Skrivefeil const useErrorHandling = (states: State) med states i flertall henger fortsatt
- style tag direkte på komnponenter. 8 steder henger fortsatt, kan taes i egen PR (opprett gjerne egen sak så jeg slipper å kommentere mer på det)

2024-11-25 12:48 UTC, merged